const data = {
    products: [
        {
            _id: '1',
            name: '나이키 슬림 맨투맨',
            category: '셔츠',
            image: '/images/p1.jpg',
            price: 119000,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: '아디다스 핏 셔츠',
            category: '셔츠',
            image: '/images/p2.jpg',
            price: 99000,
            countInStock: 20,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: '라코스테 슬림 셔츠',
            category: '셔츠',
            image: '/images/p3.jpg',
            price: 220000,
            countInStock: 0,
            brand: 'Lacoste',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: '나이키 슬림 팬츠',
            category: '바지',
            image: '/images/p4.jpg',
            price: 78000,
            countInStock: 15,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: '퓨마 슬림 팬츠',
            category: '바지',
            image: '/images/p5.jpg',
            price: 65000,
            countInStock: 5,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: '아이다스 핏 팬츠',
            category: '바지',
            image: '/images/p6.jpg',
            price: 149000,
            countInStock: 12,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
    ]
};

export default data;